package com.yuhi.sandbox;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class YojCodeSandboxApplication {

    public static void main(String[] args) {
        SpringApplication.run(YojCodeSandboxApplication.class, args);
    }

}
